#!/usr/bin/env node
/**
 * builderforce-memory hook — generated by builderforce-memory-install. Dependency-free:
 * reads only the JSON snapshot, never stands up the MCP server.
 *   --session     SessionStart: inject a small digest of durable memories.
 *   --precompact  PreCompact: remind to flush learnings before summarisation.
 *   --recall      UserPromptSubmit: contextual recall — inject memories relevant to the prompt.
 *   --capture     Stop: autonomous consolidation — block the stop until a detected
 *                 durable correction is persisted via memory_remember.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const FILE = process.env["BUILDERFORCE_MEMORY_FILE"] || path.join(os.homedir(), ".builderforce-memory", "memory.json");
const mode = process.argv[2] || "--session";

function readStdin() {
    try { return fs.readFileSync(0, "utf8"); } catch { return ""; }
}
function loadEntries() {
    try { const p = JSON.parse(fs.readFileSync(FILE, "utf8")); return Array.isArray(p) ? p : []; }
    catch { return []; }
}
function tokens(s) {
    return String(s || "").toLowerCase().split(/[^a-z0-9]+/).filter((t) => t.length >= 3);
}

// ── Per-session injection ledger ─────────────────────────────────────────────
// The SessionStart digest and the per-prompt recall both push memory CONTENT
// into the context window, where it stays for the rest of the session. Without
// dedup, a long session re-injects the same memories on every turn — unbounded
// growth that is exactly what pushes a session past 150k tokens. The ledger
// records which keys have already been surfaced THIS session so we inject each
// memory at most once. Keyed by the host-provided session_id; degrades to the
// old always-inject behaviour when no id is available.
function ledgerFile(sid) {
    const safe = String(sid || "").replace(/[^a-zA-Z0-9_.-]/g, "").slice(0, 80) || "nosession";
    return path.join(os.tmpdir(), "bfmem-injected-" + safe + ".json");
}
function loadLedger(sid) {
    try { const a = JSON.parse(fs.readFileSync(ledgerFile(sid), "utf8")); return new Set(Array.isArray(a) ? a : []); }
    catch { return new Set(); }
}
function saveLedger(sid, set) {
    if (!sid) return; // no id → no dedup state to persist (safe fallback)
    try { fs.writeFileSync(ledgerFile(sid), JSON.stringify([...set].slice(-500))); } catch { /* best effort */ }
}

if (mode === "--precompact") {
    process.stdout.write(
        "[builderforce-memory] Context is about to be compacted. Persist any durable learnings from this session — decisions, fixes, project facts, user preferences — by calling memory_remember with concise one-line facts. Recall them later with memory_recall instead of re-reading files.",
    );
    process.exit(0);
}

if (mode === "--recall") {
    let prompt = "", sid = "";
    try {
        const j = JSON.parse(readStdin() || "{}");
        prompt = typeof j.prompt === "string" ? j.prompt : "";
        sid = typeof j.session_id === "string" ? j.session_id : "";
    } catch { /* no input */ }
    if (!prompt) process.exit(0);
    const entries = loadEntries();
    if (entries.length === 0) process.exit(0);
    const q = new Set(tokens(prompt));
    if (q.size === 0) process.exit(0);
    const led = loadLedger(sid);
    const scored = entries
        .map((e) => {
            const hay = new Set(tokens([e.key, e.content, (e.tags || []).join(" ")].join(" ")));
            let score = 0;
            for (const t of q) if (hay.has(t)) score++;
            return { e, score };
        })
        .filter((x) => x.score >= 2)
        .filter((x) => !led.has(x.e.key)) // already surfaced this session → don't re-inject
        .sort((a, b) => b.score - a.score)
        .slice(0, 3);
    if (scored.length === 0) process.exit(0);
    for (const x of scored) led.add(x.e.key);
    saveLedger(sid, led);
    const lines = scored.map((x) => "• " + x.e.key + ": " + String(x.e.content || "").slice(0, 200)).join("\n");
    process.stdout.write(
        "[builderforce-memory] Relevant stored memories for this request — use these instead of re-deriving or re-reading:\n" + lines,
    );
    process.exit(0);
}

if (mode === "--capture") {
    let input = {};
    try { input = JSON.parse(readStdin() || "{}"); } catch { /* no input */ }
    if (input.stop_hook_active) process.exit(0);
    const tpath = input.transcript_path;
    if (!tpath || typeof tpath !== "string") process.exit(0);

    let raw = "";
    try {
        const stat = fs.statSync(tpath);
        const want = Math.min(stat.size, 400000);
        const fd = fs.openSync(tpath, "r");
        const buf = Buffer.alloc(want);
        fs.readSync(fd, buf, 0, want, stat.size - want);
        fs.closeSync(fd);
        raw = buf.toString("utf8");
    } catch { process.exit(0); }

    const msgs = [];
    for (const ln of raw.split("\n")) { if (ln.trim()) { try { msgs.push(JSON.parse(ln)); } catch { /* partial */ } } }

    let lastUserText = "";
    let rememberedThisTurn = false;
    for (let i = msgs.length - 1; i >= 0; i--) {
        const m = msgs[i] || {};
        const inner = m.message || m;
        const role = inner.role;
        const content = inner.content;
        if (role === "assistant" && !lastUserText) {
            if (Array.isArray(content)) for (const c of content) {
                if (c && c.type === "tool_use" && typeof c.name === "string" && c.name.includes("memory_remember")) rememberedThisTurn = true;
            }
        }
        if (role === "user" && !lastUserText) {
            let txt = "";
            if (typeof content === "string") txt = content;
            else if (Array.isArray(content)) for (const c of content) {
                if (typeof c === "string") txt += c + " ";
                else if (c && c.type === "text" && typeof c.text === "string") txt += c.text + " ";
            }
            if (txt.trim()) lastUserText = txt;
        }
    }
    if (!lastUserText || rememberedThisTurn) process.exit(0);

    const lower = lastUserText.toLowerCase();
    const SIGNALS = [
        "you have to", "you should", "you need to", "you must", "from now on", "going forward",
        "always ", "never ", "make sure", "remember to", "don't forget", "do not forget",
        "i keep telling", "i already told", "shouldn't have to", "keep having to remind",
        "you forgot", "you keep", "that's wrong", "you're wrong", "this is wrong", "stop ",
    ];
    const hit = SIGNALS.find((s) => lower.includes(s));
    if (!hit) process.exit(0);

    const snippet = lastUserText.trim().slice(0, 240);
    const reason =
        "[builderforce-memory] A durable instruction/correction was detected in the user's last message and you did NOT consolidate it this turn. " +
        "Before stopping, call memory_remember with a concise, stable-keyed fact capturing it (reuse the same key to replace a superseded one, or memory_forget it). " +
        "User said: '" + snippet + "'. If it is genuinely not durable (a one-off, or already stored), briefly say why and then stop.";
    process.stdout.write(JSON.stringify({ decision: "block", reason }));
    process.exit(0);
}

// SessionStart (default mode). Read the source + session_id so we can (a) seed
// the per-session ledger with the digest keys and (b) skip re-injecting on
// 'resume', where the earlier context — including this digest — is retained and
// a second copy would be pure waste.
let src = "startup", sessionId = "";
try {
    const j = JSON.parse(readStdin() || "{}");
    if (typeof j.source === "string") src = j.source;
    if (typeof j.session_id === "string") sessionId = j.session_id;
} catch { /* no input */ }

const entries = loadEntries();
if (entries.length === 0) {
    if (src !== "resume") process.stdout.write(
        "[builderforce-memory] Active (memory empty). Store durable facts with memory_remember and retrieve them with memory_recall instead of re-reading files or chat history — that is how token usage stays low.",
    );
    process.exit(0);
}
const ranked = entries
    .map((e) => ({ key: e.key, content: String(e.content ?? ""), importance: typeof e.importance === "number" ? e.importance : 0.5 }))
    .sort((a, b) => b.importance - a.importance)
    .slice(0, 6);

// Record the digest keys so per-prompt recall won't re-surface what's already
// on screen. Fresh window (startup/clear) → new ledger; otherwise merge.
const led = (src === "startup" || src === "clear") ? new Set() : loadLedger(sessionId);
for (const e of ranked) led.add(e.key);
saveLedger(sessionId, led);

if (src === "resume") process.exit(0); // context retained across resume — nothing to re-inject
const top = ranked.map((e) => "• " + e.key + ": " + e.content.slice(0, 180)).join("\n");
process.stdout.write(
    "[builderforce-memory] Active — token-saving memory loaded. Before re-reading files or history, call memory_recall. Store durable facts with memory_remember.\nTop memories:\n" + top,
);
