/**
 * Claude Code "memory combo" — the hooks + companion skill half of the install.
 *
 * Registering the MCP server (install.ts) gives Claude Code the memory TOOLS.
 * This module adds the behaviour that makes memory SELF-DRIVING rather than
 * advisory, so the agent doesn't have to be reminded to use it:
 *
 *   SessionStart      → inject a digest of the top durable memories.
 *   PreCompact        → flush durable learnings before the window is summarised.
 *   UserPromptSubmit  → CONTEXTUAL recall: score memories against the prompt and
 *                       inject the relevant ones (so a stored fact is retrieved at
 *                       the decision point, not just at session start).
 *   Stop              → AUTONOMOUS capture: detect a durable instruction/correction
 *                       in the user's last message and, if it wasn't consolidated
 *                       this turn, BLOCK the stop with a directive to memory_remember
 *                       (capture flows through the MCP write path — never racing the
 *                       server's snapshot).
 *
 * All four point at one generated, dependency-free hook script (DRY). The combo
 * is idempotent and backup-safe, matching install.ts.
 */

import nodePath from "node:path";
import type { FsLike } from "./install.js";
import { MEMORY_FILE_ENV } from "./server-spec.js";

/**
 * The single hook script, four modes.
 *
 * `memoryFile` is the JSON snapshot path to bake in. Pass `null` to emit a
 * script that resolves the path at RUN time instead — required for the Claude
 * Code plugin, whose files are static and machine-independent. The runtime
 * branch must stay in lockstep with `resolveMemoryFile`; `install.test.mjs`
 * asserts it does.
 */
export function bfmemHookSource(memoryFile: string | null): string {
    const fileExpr = memoryFile === null
        ? `process.env[${JSON.stringify(MEMORY_FILE_ENV)}] || path.join(os.homedir(), ".builderforce-memory", "memory.json")`
        : JSON.stringify(memoryFile);
    return `#!/usr/bin/env node
/**
 * builderforce-memory hook — generated by builderforce-memory-install. Dependency-free:
 * reads only the JSON snapshot, never stands up the MCP server.
 *   --session     SessionStart: inject a small digest of durable memories.
 *   --precompact  PreCompact: remind to flush learnings before summarisation.
 *   --recall      UserPromptSubmit: contextual recall — inject memories relevant to the prompt.
 *   --capture     Stop: autonomous consolidation — block the stop until a detected
 *                 durable correction is persisted via memory_remember.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const FILE = ${fileExpr};
const mode = process.argv[2] || "--session";

function readStdin() {
    try { return fs.readFileSync(0, "utf8"); } catch { return ""; }
}
function loadEntries() {
    try { const p = JSON.parse(fs.readFileSync(FILE, "utf8")); return Array.isArray(p) ? p : []; }
    catch { return []; }
}
function tokens(s) {
    return String(s || "").toLowerCase().split(/[^a-z0-9]+/).filter((t) => t.length >= 3);
}

// ── Per-session injection ledger ─────────────────────────────────────────────
// The SessionStart digest and the per-prompt recall both push memory CONTENT
// into the context window, where it stays for the rest of the session. Without
// dedup, a long session re-injects the same memories on every turn — unbounded
// growth that is exactly what pushes a session past 150k tokens. The ledger
// records which keys have already been surfaced THIS session so we inject each
// memory at most once. Keyed by the host-provided session_id; degrades to the
// old always-inject behaviour when no id is available.
function ledgerFile(sid) {
    const safe = String(sid || "").replace(/[^a-zA-Z0-9_.-]/g, "").slice(0, 80) || "nosession";
    return path.join(os.tmpdir(), "bfmem-injected-" + safe + ".json");
}
function loadLedger(sid) {
    try { const a = JSON.parse(fs.readFileSync(ledgerFile(sid), "utf8")); return new Set(Array.isArray(a) ? a : []); }
    catch { return new Set(); }
}
function saveLedger(sid, set) {
    if (!sid) return; // no id → no dedup state to persist (safe fallback)
    try { fs.writeFileSync(ledgerFile(sid), JSON.stringify([...set].slice(-500))); } catch { /* best effort */ }
}

if (mode === "--precompact") {
    process.stdout.write(
        "[builderforce-memory] Context is about to be compacted. Persist any durable learnings from this session — decisions, fixes, project facts, user preferences — by calling memory_remember with concise one-line facts. Recall them later with memory_recall instead of re-reading files.",
    );
    process.exit(0);
}

if (mode === "--recall") {
    let prompt = "", sid = "";
    try {
        const j = JSON.parse(readStdin() || "{}");
        prompt = typeof j.prompt === "string" ? j.prompt : "";
        sid = typeof j.session_id === "string" ? j.session_id : "";
    } catch { /* no input */ }
    if (!prompt) process.exit(0);
    const entries = loadEntries();
    if (entries.length === 0) process.exit(0);
    const q = new Set(tokens(prompt));
    if (q.size === 0) process.exit(0);
    const led = loadLedger(sid);
    const scored = entries
        .map((e) => {
            const hay = new Set(tokens([e.key, e.content, (e.tags || []).join(" ")].join(" ")));
            let score = 0;
            for (const t of q) if (hay.has(t)) score++;
            return { e, score };
        })
        .filter((x) => x.score >= 2)
        .filter((x) => !led.has(x.e.key)) // already surfaced this session → don't re-inject
        .sort((a, b) => b.score - a.score)
        .slice(0, 3);
    if (scored.length === 0) process.exit(0);
    for (const x of scored) led.add(x.e.key);
    saveLedger(sid, led);
    const lines = scored.map((x) => "• " + x.e.key + ": " + String(x.e.content || "").slice(0, 200)).join("\\n");
    process.stdout.write(
        "[builderforce-memory] Relevant stored memories for this request — use these instead of re-deriving or re-reading:\\n" + lines,
    );
    process.exit(0);
}

if (mode === "--capture") {
    let input = {};
    try { input = JSON.parse(readStdin() || "{}"); } catch { /* no input */ }
    if (input.stop_hook_active) process.exit(0);
    const tpath = input.transcript_path;
    if (!tpath || typeof tpath !== "string") process.exit(0);

    let raw = "";
    try {
        const stat = fs.statSync(tpath);
        const want = Math.min(stat.size, 400000);
        const fd = fs.openSync(tpath, "r");
        const buf = Buffer.alloc(want);
        fs.readSync(fd, buf, 0, want, stat.size - want);
        fs.closeSync(fd);
        raw = buf.toString("utf8");
    } catch { process.exit(0); }

    const msgs = [];
    for (const ln of raw.split("\\n")) { if (ln.trim()) { try { msgs.push(JSON.parse(ln)); } catch { /* partial */ } } }

    let lastUserText = "";
    let rememberedThisTurn = false;
    for (let i = msgs.length - 1; i >= 0; i--) {
        const m = msgs[i] || {};
        const inner = m.message || m;
        const role = inner.role;
        const content = inner.content;
        if (role === "assistant" && !lastUserText) {
            if (Array.isArray(content)) for (const c of content) {
                if (c && c.type === "tool_use" && typeof c.name === "string" && c.name.includes("memory_remember")) rememberedThisTurn = true;
            }
        }
        if (role === "user" && !lastUserText) {
            let txt = "";
            if (typeof content === "string") txt = content;
            else if (Array.isArray(content)) for (const c of content) {
                if (typeof c === "string") txt += c + " ";
                else if (c && c.type === "text" && typeof c.text === "string") txt += c.text + " ";
            }
            if (txt.trim()) lastUserText = txt;
        }
    }
    if (!lastUserText || rememberedThisTurn) process.exit(0);

    const lower = lastUserText.toLowerCase();
    const SIGNALS = [
        "you have to", "you should", "you need to", "you must", "from now on", "going forward",
        "always ", "never ", "make sure", "remember to", "don't forget", "do not forget",
        "i keep telling", "i already told", "shouldn't have to", "keep having to remind",
        "you forgot", "you keep", "that's wrong", "you're wrong", "this is wrong", "stop ",
    ];
    const hit = SIGNALS.find((s) => lower.includes(s));
    if (!hit) process.exit(0);

    const snippet = lastUserText.trim().slice(0, 240);
    const reason =
        "[builderforce-memory] A durable instruction/correction was detected in the user's last message and you did NOT consolidate it this turn. " +
        "Before stopping, call memory_remember with a concise, stable-keyed fact capturing it (reuse the same key to replace a superseded one, or memory_forget it). " +
        "User said: '" + snippet + "'. If it is genuinely not durable (a one-off, or already stored), briefly say why and then stop.";
    process.stdout.write(JSON.stringify({ decision: "block", reason }));
    process.exit(0);
}

// SessionStart (default mode). Read the source + session_id so we can (a) seed
// the per-session ledger with the digest keys and (b) skip re-injecting on
// 'resume', where the earlier context — including this digest — is retained and
// a second copy would be pure waste.
let src = "startup", sessionId = "";
try {
    const j = JSON.parse(readStdin() || "{}");
    if (typeof j.source === "string") src = j.source;
    if (typeof j.session_id === "string") sessionId = j.session_id;
} catch { /* no input */ }

const entries = loadEntries();
if (entries.length === 0) {
    if (src !== "resume") process.stdout.write(
        "[builderforce-memory] Active (memory empty). Store durable facts with memory_remember and retrieve them with memory_recall instead of re-reading files or chat history — that is how token usage stays low.",
    );
    process.exit(0);
}
const ranked = entries
    .map((e) => ({ key: e.key, content: String(e.content ?? ""), importance: typeof e.importance === "number" ? e.importance : 0.5 }))
    .sort((a, b) => b.importance - a.importance)
    .slice(0, 6);

// Record the digest keys so per-prompt recall won't re-surface what's already
// on screen. Fresh window (startup/clear) → new ledger; otherwise merge.
const led = (src === "startup" || src === "clear") ? new Set() : loadLedger(sessionId);
for (const e of ranked) led.add(e.key);
saveLedger(sessionId, led);

if (src === "resume") process.exit(0); // context retained across resume — nothing to re-inject
const top = ranked.map((e) => "• " + e.key + ": " + e.content.slice(0, 180)).join("\\n");
process.stdout.write(
    "[builderforce-memory] Active — token-saving memory loaded. Before re-reading files or history, call memory_recall. Store durable facts with memory_remember.\\nTop memories:\\n" + top,
);
`;
}

/** The companion skill doc that teaches the recall/remember discipline. */
export function companionSkillMd(): string {
    return `---
name: builderforce-memory
description: Token-saving persistent memory. Recall durable facts (decisions, fixes, project context, user preferences) instead of re-reading files or chat history, and remember new durable facts as you learn them.
---

# builderforce-memory — the conductor

Persistent memory backed by the \`builderforce-memory\` MCP server. The point is
**token reduction**: pull a small relevant slice from memory instead of re-reading
the full file/history. The install also wires hooks so this is largely automatic:
the SessionStart digest, contextual recall on each prompt, and an autonomous Stop
capture that won't let a durable correction go unrecorded.

## Tools
- \`memory_recall(query, [k])\` — top-K relevant memories. First move on a task.
- \`memory_get(key)\` — exact lookup by key.
- \`memory_recall_by_tag(tag)\` — everything under a tag.
- \`memory_remember(key, content, [tags], [importance])\` — store ONE durable fact.
- \`memory_forget(key)\` — drop a superseded fact.

## Discipline
Reuse a stable key to REPLACE a fact (write-through), don't append duplicates.
Store decisions, non-obvious fixes, project constraints, user preferences — one
tight line each. Not things git already records or one-off turn details.
`;
}

/** Files/paths the combo manages, derived from the Claude config dir (~/.claude). */
export interface ClaudeComboPaths {
    claudeDir: string;
    settingsFile: string;
    hookScript: string;
    companionSkill: string;
}

export function claudeComboPaths(claudeDir: string): ClaudeComboPaths {
    return {
        claudeDir,
        settingsFile: nodePath.join(claudeDir, "settings.json"),
        hookScript: nodePath.join(claudeDir, "builderforce-memory", "bfmem-hook.mjs"),
        companionSkill: nodePath.join(claudeDir, "skills", "builderforce-memory", "SKILL.md"),
    };
}

/**
 * The four events that make memory self-driving, and the hook-script mode each
 * one runs. Single source of truth for BOTH delivery shapes: the settings.json
 * merge performed by {@link installClaudeCombo}, and the static `hooks.json` a
 * Claude Code plugin ships ({@link pluginHooksConfig}).
 */
export const HOOK_EVENTS = [
    { event: "SessionStart", mode: "--session" },
    { event: "PreCompact", mode: "--precompact" },
    { event: "UserPromptSubmit", mode: "--recall" },
    { event: "Stop", mode: "--capture" },
] as const;

/** Hook-config shape shared by `settings.json` and a plugin's `hooks/hooks.json`. */
export type HookConfig = Record<string, Array<{ hooks: Array<{ type: "command"; command: string }> }>>;

/**
 * The plugin form of the combo: every event pointed at the plugin-local hook
 * script. `${CLAUDE_PLUGIN_ROOT}` is expanded by Claude Code to the installed
 * plugin directory, so the script needs no install step and no baked-in paths.
 */
export function pluginHooksConfig(scriptRelPath = "hooks/bfmem-hook.mjs"): HookConfig {
    const config: HookConfig = {};
    for (const { event, mode } of HOOK_EVENTS) {
        config[event] = [{
            hooks: [{ type: "command", command: `node "\${CLAUDE_PLUGIN_ROOT}/${scriptRelPath}" ${mode}` }],
        }];
    }
    return config;
}

/**
 * Write the hook script + companion skill and register all four hooks in
 * settings.json. Idempotent (skips a hook command already present) and
 * backup-safe (.bak before overwriting settings). Returns the events it added.
 */
export function installClaudeCombo(opts: {
    fs: FsLike;
    claudeDir: string;
    memoryFile: string;
}): { hookScript: string; addedHooks: string[]; settingsFile: string } {
    const { fs, memoryFile } = opts;
    const paths = claudeComboPaths(opts.claudeDir);

    // 1) Hook script.
    const hookDir = nodePath.dirname(paths.hookScript);
    if (!fs.existsSync(hookDir)) fs.mkdirSync(hookDir, { recursive: true });
    fs.writeFileSync(paths.hookScript, bfmemHookSource(memoryFile));

    // 2) Companion skill.
    const skillDir = nodePath.dirname(paths.companionSkill);
    if (!fs.existsSync(skillDir)) fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(paths.companionSkill, companionSkillMd());

    // 3) Merge hooks into settings.json.
    let settings: Record<string, unknown> = {};
    if (fs.existsSync(paths.settingsFile)) {
        try { settings = JSON.parse(fs.readFileSync(paths.settingsFile, "utf8")) as Record<string, unknown>; }
        catch { throw new Error("existing settings.json is not valid JSON"); }
        fs.copyFileSync(paths.settingsFile, `${paths.settingsFile}.bak`);
    }
    const hooks = (settings.hooks && typeof settings.hooks === "object" ? settings.hooks : {}) as Record<string, unknown>;
    // Compare commands by a normalized form (path separators unified, whitespace
    // collapsed, case-folded) so a re-install can't register a second copy of the
    // same hook just because an earlier run wrote "C:/…" and this one writes
    // "C:\…". Without this, Windows accumulates duplicate SessionStart/PreCompact
    // hooks that each fire — doubling the memory the combo injects every session.
    const normCmd = (c: string) => String(c ?? "").replace(/\\/g, "/").replace(/\s+/g, " ").trim().toLowerCase();
    const hookRef = normCmd(paths.hookScript);
    const added: string[] = [];
    for (const { event, mode } of HOOK_EVENTS) {
        const command = `node "${paths.hookScript}" ${mode}`;
        const arr = (Array.isArray(hooks[event]) ? hooks[event] : []) as Array<{ hooks?: Array<{ type?: string; command?: string }> }>;
        // Drop any existing group that points at OUR hook script for THIS mode
        // (any path-separator variant), then re-add exactly one canonical entry.
        // This both dedupes accidental duplicates and refreshes the command.
        const kept = arr.filter((g) => !(g.hooks || []).some((h) => {
            const n = normCmd(h.command ?? "");
            return n.includes(hookRef) && n.endsWith(mode);
        }));
        const wasPresent = kept.length !== arr.length;
        kept.push({ hooks: [{ type: "command", command }] });
        hooks[event] = kept;
        if (!wasPresent) added.push(event);
    }
    settings.hooks = hooks;
    const settingsDir = nodePath.dirname(paths.settingsFile);
    if (!fs.existsSync(settingsDir)) fs.mkdirSync(settingsDir, { recursive: true });
    fs.writeFileSync(paths.settingsFile, `${JSON.stringify(settings, null, 2)}\n`);

    return { hookScript: paths.hookScript, addedHooks: added, settingsFile: paths.settingsFile };
}
